[package]
name = "rust-example-use"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-example-lib = { git = "https://github.com/mitchallen/rust-example-lib.git", tag = "v0.1.1" }